const fallback = {
  site: { name: "TAMORA", authorName: "Tam Phan", heroEyebrow: "A quiet corner of the internet", heroTitle: "For the days you are learning to choose yourself.", heroIntro: "Honest writing about caring for your mind, building a calmer relationship with money, loving without losing yourself, and growing at your own pace.", profileImage: "", aboutTitle: "Hi, I’m Tam. I write to make life feel a little less lonely.", aboutBody: [], contactText: "If you have a thoughtful project, a story worth telling, or simply want to say hello, I’d love to hear from you.", newsletterTitle: "A little pause, delivered gently.", newsletterText: "Occasional notes on being human, finding clarity, and creating a life that feels like yours.", footerTagline: "Thoughtful notes for a gentler, braver life." },
  topics: [], posts: []
};
let data=fallback,activeTopic="All",siteSettings=fallback.site,controlSite={};
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const slugify=value=>String(value||"story").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const postUrl=p=>`story.html?story=${encodeURIComponent(p.slug||slugify(p.title))}`;
const isPublished=p=>String(p.status||'published').toLowerCase()!=='draft';
const posts=()=> (data.posts||[]).filter(isPublished);
const topicFor=name=>(data.topics||[]).find(t=>t.name===name)||{color:"#dfc4a9",icon:"✦",note:""};
const displayDate=value=>{const d=String(value||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return d;return new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${d}T00:00:00Z`))};
const readingTime=p=>{const html=p.content?new DOMParser().parseFromString(p.content,"text/html").body.textContent||"":"";const text=html||[p.lead,...(p.body||[]),p.quote].filter(Boolean).join(" ");const count=text.trim().split(/\s+/).filter(Boolean).length;return `${Math.max(1,Math.ceil(count/220))} min read`};
function postArt(p){const t=topicFor(p.category),color=p.color||t.color;return p.image?`<a class="post-art" href="${postUrl(p)}"><img src="${esc(p.image)}" alt="${esc(p.title)}" loading="lazy"></a>`:`<a class="post-art" style="--post-color:${esc(color)}" href="${postUrl(p)}"><span class="art-shape a"></span><span class="art-shape b"></span><span class="art-line"></span><span class="art-topic">${esc(t.icon)}</span></a>`}
function meta(p){return `<div class="post-meta"><span>${esc(p.category)}</span>${p.date?`<span>${esc(displayDate(p.date))}</span>`:""}<span>${esc(readingTime(p))}</span></div>`}
function renderSite(){const s={...fallback.site,...(data.site||{}),...controlSite};siteSettings=s;$$('[data-site-name]').forEach(el=>el.textContent=s.name||'TAMORA');$$('[data-author-name]').forEach(el=>el.textContent=s.authorName||'Tam Phan');if($('[data-hero-eyebrow]'))$('[data-hero-eyebrow]').textContent=s.heroEyebrow||'';if($('[data-hero-title]'))$('[data-hero-title]').textContent=s.heroTitle||'';if($('[data-hero-intro]'))$('[data-hero-intro]').textContent=s.heroIntro||'';if(s.profileImage&&$('[data-profile-image]')){const img=$('[data-profile-image]');img.src=s.profileImage;img.hidden=false}if($('[data-contact-text]'))$('[data-contact-text]').textContent=s.contactText||'';if($('[data-newsletter-title]'))$('[data-newsletter-title]').textContent=s.newsletterTitle||'';if($('[data-newsletter-text]'))$('[data-newsletter-text]').textContent=s.newsletterText||'';if($('[data-footer-tagline]'))$('[data-footer-tagline]').textContent=s.tagline||s.footerTagline||'';if($('[data-about-title]'))$('[data-about-title]').textContent=s.aboutTitle||'';if($('[data-about-body]'))$('[data-about-body]').innerHTML=(s.aboutBody||[]).map(x=>`<p>${esc(x)}</p>`).join('')}
function renderFront(){const all=[...posts()];if(!all.length){$('#front-page-lead').innerHTML='';return}const idx=Math.max(0,all.findIndex(p=>p.featured));const lead=all.splice(idx,1)[0],rail=all.slice(0,3);$('#front-page-lead').innerHTML=`<article class="lead-story reveal">${postArt(lead)}${meta(lead)}<h2><a href="${postUrl(lead)}">${esc(lead.title)}</a></h2><p class="lead-excerpt">${esc(lead.excerpt)}</p><p class="byline">By ${esc(lead.author||siteSettings.authorName||'Tam Phan')}</p></article><aside class="front-page-rail">${rail.map((p,i)=>`<article class="rail-story reveal">${i===0?postArt(p):''}${meta(p)}<h3><a href="${postUrl(p)}">${esc(p.title)}</a></h3><p>${esc(p.excerpt)}</p></article>`).join('')}</aside>`}
function renderTopics(){const used=[...new Set(posts().map(p=>p.category))];const source=[...(data.topics||[])];used.forEach(name=>{if(!source.some(t=>t.name===name))source.push({name,icon:'✦',note:'',color:'#dfc4a9'})});$('#topic-grid').innerHTML=source.map(t=>`<a class="topic-card reveal" style="--topic-color:${esc(t.color||'#dfc4a9')}" href="#journal" data-filter="${esc(t.name)}"><span class="topic-icon">${esc(t.icon||'✦')}</span><div><h3>${esc(t.name)}</h3><p>${esc(t.note||'')}</p></div></a>`).join('');$('#filter-pills').innerHTML=['All',...source.map(t=>t.name)].map(name=>`<button class="filter-pill${name==='All'?' active':''}" data-topic="${esc(name)}">${esc(name)}</button>`).join('')}
function leadCard(p){return `<article class="section-lead-story reveal">${postArt(p)}<div>${meta(p)}<h3><a href="${postUrl(p)}">${esc(p.title)}</a></h3><p>${esc(p.excerpt)}</p><a class="read-link" href="${postUrl(p)}">Read the story ↗</a></div></article>`}
function compact(p){return `<article class="compact-story reveal">${meta(p)}<h4><a href="${postUrl(p)}">${esc(p.title)}</a></h4><p>${esc(p.excerpt)}</p></article>`}
function renderJournal(){const q=($('#post-search')?.value||'').trim().toLowerCase();const featured=posts().find(p=>p.featured);const filtered=posts().filter(p=>p!==featured).filter(p=>(activeTopic==='All'||p.category===activeTopic)&&(!q||`${p.title} ${p.excerpt} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q)));const groups=activeTopic==='All'?[...new Set(posts().map(p=>p.category))]:[activeTopic];$('#topic-sections').innerHTML=groups.map(name=>{const items=filtered.filter(p=>p.category===name);if(!items.length)return'';const t=topicFor(name);return `<section class="journal-group" style="--topic-color:${esc(t.color)}"><div class="group-heading"><span>${esc(t.icon)}</span><div><h3>${esc(name)}</h3><small>${esc(t.note||'Thoughtful notes and practical ideas')}</small></div><p>${items.length} ${items.length===1?'story':'stories'}</p></div><div class="newspaper-section-grid">${leadCard(items[0])}<div class="section-story-list">${items.slice(1).map(compact).join('')}</div></div></section>`}).join('');$('#empty-state').hidden=filtered.length>0;$('#result-count').textContent=`${filtered.length} ${filtered.length===1?'story':'stories'}${activeTopic==='All'?'':` in ${activeTopic}`}${q?` matching “${q}”`:''}`;$$('.filter-pill').forEach(b=>b.classList.toggle('active',b.dataset.topic===activeTopic));reveal()}
function bind(){$('#post-search')?.addEventListener('input',renderJournal);$('#filter-pills')?.addEventListener('click',e=>{const b=e.target.closest('[data-topic]');if(!b)return;activeTopic=b.dataset.topic;renderJournal()});$('#topic-grid')?.addEventListener('click',e=>{const a=e.target.closest('[data-filter]');if(!a)return;activeTopic=a.dataset.filter;renderJournal()});const menu=$('.menu-toggle');if(menu)menu.onclick=()=>{const n=$('#site-nav');const open=n.classList.toggle('open');menu.setAttribute('aria-expanded',open)};const btn=$('#newsletter-form button');if(btn){if(siteSettings.newsletterUrl){$('#newsletter-form').onsubmit=e=>{e.preventDefault();location.href=siteSettings.newsletterUrl}}else{btn.type='button';btn.disabled=true;btn.textContent='Letters coming soon'}}}
function reveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){$$('.reveal').forEach(el=>el.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.05});$$('.reveal:not(.visible)').forEach(el=>io.observe(el))}
async function init(){try{const [siteRes,controlRes]=await Promise.all([fetch(`content/site.json?fresh=${Date.now()}`,{cache:'no-store'}),fetch(`content/control.json?fresh=${Date.now()}`,{cache:'no-store'})]);if(siteRes.ok)data=await siteRes.json();if(controlRes.ok){const control=await controlRes.json();controlSite=control.site||{}}}catch{}renderSite();renderFront();renderTopics();renderJournal();bind();reveal();if($('#year'))$('#year').textContent=new Date().getFullYear()}
init();