const fallback={site:{name:"Softly, Tam",authorName:"Tam Phan",logoImage:"",favicon:"",heroEyebrow:"A quiet corner of the internet",heroTitle:"For the days you are learning to choose yourself.",heroIntro:"Honest writing about caring for your mind, building a calmer relationship with money, loving without losing yourself, and growing at your own pace.",profileImage:"",aboutTitle:"Hi, I’m Tam. I write to make life feel a little less lonely.",aboutBody:["I’m a content writer, curious observer, and lifelong student of what makes us human.","No perfect routines. Just thoughtful stories and grounded ideas for becoming more at home in your own life."],contactText:"If you have a thoughtful project, a story worth telling, or simply want to say hello, I’d love to hear from you.",newsletterTitle:"A little pause, delivered gently.",newsletterText:"Occasional notes on being human, finding clarity, and creating a life that feels like yours.",footerTagline:"Thoughtful notes for a gentler, braver life.",email:"",facebook:"",instagram:"",tiktok:""},topics:[],posts:[]};
let data=fallback,activeTopic="All",siteSettings=fallback.site;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const escapeHtml=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const slugify=v=>String(v||"story").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const postUrl=p=>`story.html?story=${encodeURIComponent(p.slug||slugify(p.title))}`;
const topicFor=name=>(data.topics||[]).find(t=>t.name===name)||{color:"#dfc4a9",icon:"✦"};
const displayDate=value=>{const d=String(value||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return d;return new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${d}T00:00:00Z`))};
const readingTime=p=>{const html=p.content?new DOMParser().parseFromString(p.content,"text/html").body.textContent||"":"";const text=html||[p.lead,...(p.body||[]),p.quote].filter(Boolean).join(" ");const words=text.trim().split(/\s+/).filter(Boolean).length;return`${Math.max(1,Math.ceil(words/220))} min read`};
function prepareHeroAnimation(){const hero=$('.editorial-intro'),title=$('[data-hero-title]');if(!hero||!title)return;const words=title.textContent.trim().split(/\s+/);title.setAttribute('aria-label',words.join(' '));title.innerHTML=words.map((w,i)=>`<span class="hero-word" style="--word-index:${i}" aria-hidden="true">${escapeHtml(w)}</span>`).join(' ');requestAnimationFrame(()=>requestAnimationFrame(()=>hero.classList.add('is-entered')))}
function postArt(p){const t=topicFor(p.category),color=p.color||t.color;return p.image?`<a class="post-art" href="${postUrl(p)}"><img src="${escapeHtml(p.image)}" alt="${escapeHtml(p.title)}" loading="lazy"></a>`:`<a class="post-art" style="--post-color:${escapeHtml(color)}" href="${postUrl(p)}" aria-label="Read ${escapeHtml(p.title)}"><span class="art-shape a"></span><span class="art-shape b"></span><span class="art-line"></span><span class="art-topic">${escapeHtml(t.icon)}</span></a>`}
function meta(p){return`<div class="post-meta"><span>${escapeHtml(p.category)}</span>${p.date?`<span>${escapeHtml(displayDate(p.date))}</span>`:""}<span>${escapeHtml(readingTime(p))}</span></div>`}
function renderSite(){const s={...fallback.site,...(data.site||{})};siteSettings=s;document.title=`${s.name} — Notes for a gentler life`;const desc=s.heroIntro||fallback.site.heroIntro;document.querySelector('meta[name="description"]').content=desc;document.querySelector('meta[property="og:title"]').content=document.title;document.querySelector('meta[property="og:description"]').content=desc;$$('[data-site-name]').forEach(el=>el.textContent=s.name);$$('[data-author-name]').forEach(el=>el.textContent=s.authorName||'Tam Phan');$('[data-hero-eyebrow]').textContent=s.heroEyebrow;$('[data-hero-title]').textContent=s.heroTitle;$('[data-hero-intro]').textContent=s.heroIntro;if(s.profileImage){const img=$('[data-profile-image]');if(img){img.src=s.profileImage;img.alt=`Portrait of ${s.name}`;img.hidden=false}}const parts=(s.aboutTitle||'').split('. ');$('[data-about-title]').innerHTML=`${escapeHtml(parts.shift()||'')}.${parts.length?`<br><em>${escapeHtml(parts.join('. '))}</em>`:''}`;$('[data-about-body]').innerHTML=(s.aboutBody||[]).map(x=>`<p>${escapeHtml(x)}</p>`).join('');$('[data-contact-text]').textContent=s.contactText||fallback.site.contactText;$('[data-newsletter-title]').textContent=s.newsletterTitle;$('[data-newsletter-text]').textContent=s.newsletterText;$('[data-footer-tagline]').textContent=s.footerTagline;$$('[data-contact-email]').forEach(el=>{if(s.email){el.href=`mailto:${s.email}`;el.hidden=false}else el.hidden=true})}
function renderFrontPage(){const posts=[...(data.posts||[])];if(!posts.length){$('#front-page-lead').innerHTML='';return}const i=Math.max(0,posts.findIndex(p=>p.featured)),lead=posts.splice(i,1)[0],rail=posts.slice(0,3);$('#front-page-lead').innerHTML=`<article class="lead-story reveal">${postArt(lead)}${meta(lead)}<h2><a href="${postUrl(lead)}">${escapeHtml(lead.title)}</a></h2><p class="lead-excerpt">${escapeHtml(lead.excerpt)}</p><p class="byline">By ${escapeHtml(lead.author||siteSettings.authorName||'Tam Phan')}</p></article><aside class="front-page-rail">${rail.map((p,n)=>`<article class="rail-story reveal">${n===0?postArt(p):''}${meta(p)}<h3><a href="${postUrl(p)}">${escapeHtml(p.title)}</a></h3><p>${escapeHtml(p.excerpt)}</p></article>`).join('')}</aside>`}
function renderTopics(){const topics=data.topics||[];$('#topic-grid').innerHTML=topics.map(t=>`<a class="topic-card reveal" style="--topic-color:${escapeHtml(t.color||'#dfc4a9')}" href="#journal" data-filter="${escapeHtml(t.name)}"><span class="topic-icon">${escapeHtml(t.icon)}</span><div><h3>${escapeHtml(t.name)}</h3><p>${escapeHtml(t.note)}</p></div></a>`).join('');$('#filter-pills').innerHTML=['All',...topics.map(t=>t.name)].map(n=>`<button class="filter-pill${n==='All'?' active':''}" data-topic="${escapeHtml(n)}">${escapeHtml(n)}</button>`).join('')}
function sectionLead(p){return`<article class="section-lead-story reveal">${postArt(p)}<div>${meta(p)}<h3><a href="${postUrl(p)}">${escapeHtml(p.title)}</a></h3><p>${escapeHtml(p.excerpt)}</p><a class="read-link" href="${postUrl(p)}">Read the story <span>↗</span></a></div></article>`}
function compactStory(p){return`<article class="compact-story reveal">${meta(p)}<h4><a href="${postUrl(p)}">${escapeHtml(p.title)}</a></h4><p>${escapeHtml(p.excerpt)}</p></article>`}
function renderJournal(){const q=($('#post-search').value||'').trim().toLowerCase(),featured=(data.posts||[]).find(p=>p.featured);const posts=(data.posts||[]).filter(p=>p!==featured).filter(p=>(activeTopic==='All'||p.category===activeTopic)&&(!q||`${p.title} ${p.excerpt} ${(p.tags||[]).join(' ')}`.toLowerCase().includes(q)));const groups=activeTopic==='All'?(data.topics||[]).map(t=>t.name):[activeTopic];$('#topic-sections').innerHTML=groups.map(name=>{const items=posts.filter(p=>p.category===name);if(!items.length)return'';const t=topicFor(name),lead=items[0],rest=items.slice(1);return`<section class="journal-group" style="--topic-color:${escapeHtml(t.color)}"><div class="group-heading"><span>${escapeHtml(t.icon)}</span><div><h3>${escapeHtml(name)}</h3><small>${escapeHtml(t.note||'Thoughtful notes and practical ideas')}</small></div><p>${items.length} ${items.length===1?'story':'stories'}</p></div><div class="newspaper-section-grid">${sectionLead(lead)}<div class="section-story-list">${rest.map(compactStory).join('')}</div></div></section>`}).join('');$('#empty-state').hidden=posts.length>0;$('#result-count').textContent=`${posts.length} ${posts.length===1?'story':'stories'}${activeTopic==='All'?'':` in ${activeTopic}`}${q?` matching “${q}”`:''}`;$$('.filter-pill').forEach(b=>b.classList.toggle('active',b.dataset.topic===activeTopic));reveal()}
function bind(){$('#post-search').addEventListener('input',renderJournal);$('#filter-pills').addEventListener('click',e=>{const b=e.target.closest('[data-topic]');if(!b)return;activeTopic=b.dataset.topic;renderJournal()});$('#topic-grid').addEventListener('click',e=>{const a=e.target.closest('[data-filter]');if(!a)return;activeTopic=a.dataset.filter;renderJournal()});const menu=$('.menu-toggle');if(menu)menu.onclick=()=>{const n=$('#site-nav'),open=n.classList.toggle('open');menu.setAttribute('aria-expanded',open)};const btn=$('#newsletter-form button');if(siteSettings.newsletterUrl){$('#newsletter-form').onsubmit=e=>{e.preventDefault();location.href=siteSettings.newsletterUrl}}else{btn.type='button';btn.disabled=true;btn.textContent='Letters coming soon'}}
function reveal(){if(matchMedia('(prefers-reduced-motion: reduce)').matches){$$('.reveal').forEach(el=>el.classList.add('visible'));return}const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.05});$$('.reveal:not(.visible)').forEach(el=>io.observe(el))}
async function init(){try{const r=await fetch(`content/site.json?fresh=${Date.now()}`,{cache:'no-store'});if(r.ok)data=await r.json()}catch{}renderSite();prepareHeroAnimation();renderFrontPage();renderTopics();renderJournal();bind();reveal();$('#year').textContent=new Date().getFullYear()}
init();
