(()=>{
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const safeUrl=v=>{try{const x=String(v||'').trim();if(!x)return'';if(/^(mailto:|tel:|#|\/)/i.test(x))return x;const u=new URL(x,location.href);return['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fetchJson=async p=>{try{const r=await fetch(`${p}?v=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():{}}catch{return{}}};
function setMeta(c){const s=c.seo||{},site=c.site||{};if(s.siteTitle)document.title=s.siteTitle;const md=$('meta[name="description"]');if(md&&s.metaDescription)md.content=s.metaDescription;const ogt=$('meta[property="og:title"]');if(ogt&&s.siteTitle)ogt.content=s.siteTitle;const ogd=$('meta[property="og:description"]');if(ogd&&s.metaDescription)ogd.content=s.metaDescription;if(s.socialImage){let m=$('meta[property="og:image"]');if(!m){m=document.createElement('meta');m.setAttribute('property','og:image');document.head.appendChild(m)}m.content=s.socialImage}if(s.canonicalUrl){let l=$('link[rel="canonical"]');if(!l){l=document.createElement('link');l.rel='canonical';document.head.appendChild(l)}l.href=s.canonicalUrl}if(site.defaultLanguage)document.documentElement.lang=site.defaultLanguage}
function announcement(c){$('.announcement-bar')?.remove();const a=c.announcement||{};if(!a.enabled||!a.text)return;const b=document.createElement('div');b.className='announcement-bar';b.append(document.createTextNode(a.text));const u=safeUrl(a.url);if(u&&a.linkLabel){const l=document.createElement('a');l.href=u;l.textContent=a.linkLabel;if(a.newTab){l.target='_blank';l.rel='noopener noreferrer'}b.appendChild(l)}const x=document.createElement('button');x.type='button';x.className='announcement-close';x.setAttribute('aria-label','Close announcement');x.textContent='×';x.onclick=()=>b.remove();b.appendChild(x);document.body.prepend(b)}
function menu(c,p){const n=$('#site-nav');if(!n)return;n.replaceChildren();const core=(c.menu||[]).filter(x=>x.enabled!==false);const custom=(p.pages||[]).filter(x=>x.published&&x.showInMenu).sort((a,b)=>(a.order||0)-(b.order||0)).map(x=>({label:x.menuLabel||x.title,url:`page.html?page=${encodeURIComponent(x.slug)}`}));[...core,...custom].forEach(x=>{const u=safeUrl(x.url)||x.url;if(!u)return;const a=document.createElement('a');a.href=u;a.textContent=x.label||'Link';if(x.newTab){a.target='_blank';a.rel='noopener noreferrer'}n.appendChild(a)})}
function ctas(c){$$('.global-cta-wrap').forEach(x=>x.remove());const items=(c.ctaButtons||[]).filter(x=>x.enabled!==false&&x.label&&x.url);if(!items.length)return;const host=$('.hero-actions')||$('.editorial-intro');if(!host)return;const wrap=document.createElement('span');wrap.className='global-cta-wrap';items.forEach(x=>{const a=document.createElement('a');a.href=safeUrl(x.url)||x.url;a.textContent=x.label;a.className=x.style==='text'?'text-link':`button ${x.style==='secondary'?'secondary':'primary'}`;if(x.newTab){a.target='_blank';a.rel='noopener noreferrer'}wrap.appendChild(a)});host.appendChild(wrap)}
function projectSection(d){const list=(d.projects||[]).filter(x=>x.published!==false).sort((a,b)=>(a.order||0)-(b.order||0));const s=document.createElement('section');s.id='projects';s.className='projects-section control-section';s.dataset.controlSection='projects';s.innerHTML=`<div class="section-shell"><div class="control-section-heading"><div><p class="eyebrow">Selected work</p><h2>Projects & videos.</h2></div><p>Selected creative work, stories and experiments.</p></div><div class="projects-grid">${list.map(p=>`<article class="project-card" style="--card-accent:${esc(p.color||'#d98168')}">${p.thumbnail?`<img src="${esc(p.thumbnail)}" alt="${esc(p.title)}">`:''}<div class="project-meta"><span>${esc(p.category||'Project')}</span>${p.views?`<span>${esc(p.views)} views</span>`:''}${p.likes?`<span>${esc(p.likes)} likes</span>`:''}</div><h3>${esc(p.title)}</h3><p>${esc(p.description||'')}</p>${p.videoUrl?`<a class="read-link" href="${esc(p.videoUrl)}" target="_blank" rel="noopener noreferrer">Watch video ↗</a>`:''}${p.ctaUrl?` <a class="read-link" href="${esc(p.ctaUrl)}">${esc(p.ctaLabel||'View project')} ↗</a>`:''}</article>`).join('')}</div></div>`;return s}
function caseSection(d){const list=(d.caseStudies||[]).filter(x=>x.published).sort((a,b)=>(a.order||0)-(b.order||0));const s=document.createElement('section');s.id='case-studies';s.className='case-studies-section control-section';s.dataset.controlSection='caseStudies';s.innerHTML=`<div class="section-shell"><div class="control-section-heading"><div><p class="eyebrow">Case studies</p><h2>How the work came together.</h2></div></div><div class="case-grid">${list.map(p=>`<article class="case-card" style="--card-accent:${esc(p.color||'#b8c9db')}">${p.images?.[0]?`<img src="${esc(p.images[0])}" alt="${esc(p.title)}">`:''}<h3>${esc(p.title)}</h3><p>${esc(p.summary||'')}</p><a class="read-link" href="case-study.html?case=${encodeURIComponent(p.slug)}">Read case study ↗</a></article>`).join('')}</div></div>`;return s}
function sections(c,p,k){const m=$('main#top');if(!m)return;let blog=$('[data-control-section="blog"]');if(!blog){blog=document.createElement('div');blog.dataset.controlSection='blog';blog.className='control-section';const f=$('.front-page'),d=$('.journal-desk');f?.before(blog);if(f)blog.appendChild(f);if(d)blog.appendChild(d)}$('[data-control-section="projects"]')?.remove();$('[data-control-section="caseStudies"]')?.remove();m.appendChild(projectSection(p));m.appendChild(caseSection(k));const map={hero:$('.editorial-intro'),projects:$('[data-control-section="projects"]'),blog,caseStudies:$('[data-control-section="caseStudies"]'),topics:$('#topics'),about:$('#about'),contact:$('#contact'),newsletter:$('#letters')};(c.homepage?.sections||[]).slice().sort((a,b)=>(a.order||0)-(b.order||0)).forEach(x=>{const el=map[x.id];if(!el)return;el.hidden=x.enabled===false;el.dataset.controlSection=x.id;m.appendChild(el)})}
function brand(c){const s=c.site||{},h=c.homepage||{};if(s.name)$$('[data-site-name]').forEach(x=>x.textContent=s.name);if(s.authorName)$$('[data-author-name]').forEach(x=>x.textContent=s.authorName);if(s.tagline&&$('[data-footer-tagline]'))$('[data-footer-tagline]').textContent=s.tagline;if(h.heroEyebrow&&$('[data-hero-eyebrow]'))$('[data-hero-eyebrow]').textContent=h.heroEyebrow;if(h.heroTitle&&$('[data-hero-title]'))$('[data-hero-title]').textContent=h.heroTitle;if(h.heroIntro&&$('[data-hero-intro]'))$('[data-hero-intro]').textContent=h.heroIntro}
async function init(){const [c,p,k,pg]=await Promise.all([fetchJson('content/control.json'),fetchJson('content/projects.json'),fetchJson('content/case-studies.json'),fetchJson('content/pages.json')]);setMeta(c);announcement(c);brand(c);menu(c,pg);ctas(c);sections(c,p,k)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,250),{once:true});else setTimeout(init,250);
})();