(() => {
  const safeUrl=value=>{try{const raw=String(value||'').trim();if(!raw)return'';if(/^(mailto:|tel:)/i.test(raw))return raw;const u=new URL(raw,location.href);return['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
  const fetchJson=async path=>{try{const r=await fetch(`${path}?sync=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():{}}catch{return{}}};
  const iconMap={
    email:'assets/icons/email.svg',
    telegram:'assets/icons/telegram.svg',
    facebook:'assets/icons/facebook.svg',
    instagram:'assets/icons/instagram.svg',
    tiktok:'assets/icons/tiktok.svg',
    whatsapp:'assets/icons/whatsapp.svg',
    linkedin:'assets/icons/linkedin.svg',
    youtube:'assets/icons/youtube.svg',
    phone:'assets/icons/phone.svg',
    telephone:'assets/icons/phone.svg'
  };
  function ensureStyles(){if(document.querySelector('link[data-branding-sync]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='branding-sync.css?v=3';l.dataset.brandingSync='true';document.head.appendChild(l)}
  function setFavicon(value){const href=safeUrl(value)||'assets/site-icon.svg';let l=document.querySelector('link[rel="icon"]');if(!l){l=document.createElement('link');l.rel='icon';document.head.appendChild(l)}l.href=href}
  function setBrand(site){document.querySelectorAll('[data-site-name]').forEach(el=>el.textContent=site.name||'Softly, Tam');document.querySelectorAll('[data-author-name]').forEach(el=>el.textContent=site.authorName||'Tam Phan');const logo=safeUrl(site.logoImage);document.querySelectorAll('.brand-mark').forEach(mark=>{mark.replaceChildren();mark.classList.toggle('has-image',Boolean(logo));if(logo){const img=document.createElement('img');img.src=logo;img.alt='';mark.appendChild(img)}else mark.textContent='S'});setFavicon(site.favicon)}
  function channelsFrom(site,contact){const configured=Array.isArray(contact?.channels)&&contact.channels.length?contact.channels:Array.isArray(site.contactChannels)?site.contactChannels:[];const list=configured.filter(x=>x&&x.enabled!==false&&x.label&&safeUrl(x.url)).map(x=>({label:String(x.label),icon:String(x.icon||''),url:safeUrl(x.url),note:String(x.note||''),showInContact:x.showInContact!==false,showInFooter:x.showInFooter!==false,newTab:x.newTab!==false}));if(list.length)return list;return[['Facebook','',site.facebook],['Instagram','',site.instagram],['TikTok','',site.tiktok]].map(([label,icon,url])=>({label,icon,url:safeUrl(url),showInContact:true,showInFooter:true,newTab:true})).filter(x=>x.url)}
  function iconPath(label){return iconMap[String(label||'').trim().toLowerCase()]||''}
  function makeLink(ch,cls=''){const a=document.createElement('a');a.href=ch.url;a.className=cls;if(ch.newTab&&!/^(mailto:|tel:)/i.test(ch.url)){a.target='_blank';a.rel='noopener noreferrer'}const mapped=iconPath(ch.label);if(mapped){const img=document.createElement('img');img.className='channel-logo';img.src=mapped;img.alt='';a.appendChild(img)}else if(ch.icon){const i=document.createElement('span');i.className='channel-symbol';i.textContent=ch.icon;a.appendChild(i)}const t=document.createElement('span');t.className='channel-label';t.textContent=ch.label;a.appendChild(t);if(ch.note)a.title=ch.note;return a}
  function setChannels(list){document.querySelectorAll('.footer-social-inline,.dynamic-social-links').forEach(el=>el.remove());document.querySelectorAll('[data-social-instagram]').forEach(el=>el.remove());document.querySelectorAll('.footer-links').forEach(footer=>{const items=list.filter(x=>x.showInFooter);if(!items.length)return;const wrap=document.createElement('span');wrap.className='dynamic-social-links';items.forEach(x=>wrap.appendChild(makeLink(x,'footer-channel-link')));footer.appendChild(wrap)});const contact=document.querySelector('#contact');if(contact){let row=contact.querySelector('.social-row');if(!row){row=document.createElement('div');row.className='social-row dynamic-contact-channels';(contact.querySelector('.contact-intro')||contact.querySelector('.contact-inner>div:last-child')||contact).appendChild(row)}row.replaceChildren();const items=list.filter(x=>x.showInContact);items.forEach(x=>row.appendChild(makeLink(x,'social-chip channel-chip')));row.hidden=!items.length}}
  function patchContact(contact,site){const email=String(contact?.recipientEmail||site.email||'').trim();const text=contact?.text;if(text)document.querySelectorAll('[data-contact-text],.contact-lead').forEach(el=>el.textContent=text);const form=document.querySelector('#contact-form');if(form&&email)form.action=`https://formsubmit.co/${encodeURIComponent(email)}`;document.querySelectorAll('[data-contact-email]').forEach(el=>{if(email){el.href=`mailto:${email}`;el.hidden=false}else el.hidden=true})}
  async function sync(){ensureStyles();const [legacy,control]=await Promise.all([fetchJson('content/site.json'),fetchJson('content/control.json')]);const site={...(legacy.site||{}),...(control.site||{})};const contact=control.contact||{};setBrand(site);setChannels(channelsFrom(site,contact));patchContact(contact,site);const tagline=document.querySelector('[data-footer-tagline]');if(tagline&&(site.tagline||site.footerTagline))tagline.textContent=site.tagline||site.footerTagline}
  function start(){sync();[800,1800,3500].forEach(ms=>setTimeout(sync,ms))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();