(() => {
  const safeUrl=value=>{try{const raw=String(value||'').trim();if(!raw)return'';if(/^(mailto:|tel:)/i.test(raw))return raw;const u=new URL(raw,location.href);return['http:','https:'].includes(u.protocol)?u.href:''}catch{return''}};
  const fetchJson=async path=>{try{const r=await fetch(`${path}?sync=${Date.now()}`,{cache:'no-store'});return r.ok?await r.json():{}}catch{return{}}};
  const iconMap={email:'assets/icons/email.svg',telegram:'assets/icons/telegram.svg',facebook:'assets/icons/facebook.svg',instagram:'assets/icons/instagram.svg',tiktok:'assets/icons/tiktok.svg',whatsapp:'assets/icons/whatsapp.svg',linkedin:'assets/icons/linkedin.svg',youtube:'assets/icons/youtube.svg',phone:'assets/icons/phone.svg',telephone:'assets/icons/phone.svg'};
  function ensureStyles(){if(document.querySelector('link[data-branding-sync]'))return;const l=document.createElement('link');l.rel='stylesheet';l.href='branding-sync.css?v=7';l.dataset.brandingSync='true';document.head.appendChild(l)}
  function setFavicon(value){const href=safeUrl(value)||'assets/site-icon.svg';let l=document.querySelector('link[rel="icon"]');if(!l){l=document.createElement('link');l.rel='icon';document.head.appendChild(l)}l.href=href}
  function setBrand(site){document.querySelectorAll('[data-site-name]').forEach(el=>el.textContent=site.name||'Softly, Tam');document.querySelectorAll('[data-author-name]').forEach(el=>el.textContent=site.authorName||'Tam Phan');const logo=safeUrl(site.logoImage);document.querySelectorAll('.brand-mark').forEach(mark=>{mark.replaceChildren();mark.classList.toggle('has-image',Boolean(logo));if(logo){const img=document.createElement('img');img.src=logo;img.alt='';mark.appendChild(img)}else mark.textContent='S'});setFavicon(site.favicon)}
  function channelsFrom(site,contact){const configured=Array.isArray(contact?.channels)&&contact.channels.length?contact.channels:Array.isArray(site.contactChannels)?site.contactChannels:[];if(configured.length){return configured.filter(x=>x&&x.enabled!==false&&x.label).map(x=>({label:String(x.label),icon:String(x.icon||''),url:safeUrl(x.url),note:String(x.note||''),showInContact:x.showInContact!==false,showInFooter:x.showInFooter!==false,newTab:x.newTab!==false,placeholder:!safeUrl(x.url)}))}return[['Facebook','',site.facebook],['Instagram','',site.instagram],['TikTok','',site.tiktok]].map(([label,icon,url])=>({label,icon,url:safeUrl(url),showInContact:true,showInFooter:true,newTab:true,placeholder:!safeUrl(url)}))}
  function iconPath(label){return iconMap[String(label||'').trim().toLowerCase()]||''}
  function appendIcon(el,ch){const mapped=iconPath(ch.label);if(mapped){const img=document.createElement('img');img.className='channel-logo';img.src=mapped;img.alt='';el.appendChild(img)}else if(ch.icon){const i=document.createElement('span');i.className='channel-symbol';i.textContent=ch.icon;el.appendChild(i)}}
  function makeContactChip(ch){const el=ch.url?document.createElement('a'):document.createElement('span');el.className='contact-channel-chip'+(ch.placeholder?' is-placeholder':'');if(ch.url){el.href=ch.url;if(ch.newTab&&!/^(mailto:|tel:)/i.test(ch.url)){el.target='_blank';el.rel='noopener noreferrer'}}appendIcon(el,ch);const label=document.createElement('span');label.className='channel-label';label.textContent=ch.label;el.appendChild(label);if(ch.note){const note=document.createElement('span');note.className='channel-note';note.textContent='· '+ch.note;el.appendChild(note)}if(ch.placeholder)el.setAttribute('aria-disabled','true');return el}
  function makeFooterLink(ch){if(!ch.url)return null;const a=document.createElement('a');a.href=ch.url;a.className='footer-channel-link';if(ch.newTab&&!/^(mailto:|tel:)/i.test(ch.url)){a.target='_blank';a.rel='noopener noreferrer'}appendIcon(a,ch);const t=document.createElement('span');t.className='channel-label';t.textContent=ch.label;a.appendChild(t);return a}
  function setChannels(list){document.querySelectorAll('.footer-social-inline,.dynamic-social-links').forEach(el=>el.remove());document.querySelectorAll('[data-social-instagram]').forEach(el=>el.remove());document.querySelectorAll('.footer-links').forEach(footer=>{const items=list.filter(x=>x.showInFooter&&x.url);if(!items.length)return;const wrap=document.createElement('span');wrap.className='dynamic-social-links';items.forEach(x=>{const link=makeFooterLink(x);if(link)wrap.appendChild(link)});footer.appendChild(wrap)});const contact=document.querySelector('#contact');if(contact){let row=contact.querySelector('.social-row');if(!row){row=document.createElement('div');row.className='social-row dynamic-contact-channels';(contact.querySelector('.contact-intro')||contact.querySelector('.contact-inner>div:last-child')||contact).appendChild(row)}row.replaceChildren();row.classList.add('dynamic-contact-channels');const items=list.filter(x=>x.showInContact);items.forEach(x=>row.appendChild(makeContactChip(x)));row.hidden=!items.length}}
  function patchContact(contact,site){const email=String(contact?.recipientEmail||site.email||'').trim();const text=contact?.text;if(text)document.querySelectorAll('[data-contact-text],.contact-lead').forEach(el=>el.textContent=text);const form=document.querySelector('#contact-form');if(form&&email)form.action=`https://formsubmit.co/${encodeURIComponent(email)}`;document.querySelectorAll('[data-contact-email]').forEach(el=>{if(email){el.href=`mailto:${email}`;el.hidden=false}else el.hidden=true})}
  async function sync(){ensureStyles();const [legacy,control]=await Promise.all([fetchJson('content/site.json'),fetchJson('content/control.json')]);const site={...(legacy.site||{}),...(control.site||{})};const contact=control.contact||{};setBrand(site);setChannels(channelsFrom(site,contact));patchContact(contact,site);const tagline=document.querySelector('[data-footer-tagline]');if(tagline&&(site.tagline||site.footerTagline))tagline.textContent=site.tagline||site.footerTagline}
  function start(){sync();[700,1600,3200].forEach(ms=>setTimeout(sync,ms))}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();