const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const escapeHtml=value=>String(value??"").replace(/[&<>'\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'\"':"&quot;"}[c]));
const slugify=value=>String(value||"story").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");
const isPublished=p=>String(p.status||'published').toLowerCase()!=='draft';
let data,control={};
function safeRichHtml(html){const doc=new DOMParser().parseFromString(String(html||""),"text/html");doc.querySelectorAll("script,iframe,object,embed,style").forEach(el=>el.remove());doc.querySelectorAll("*").forEach(el=>[...el.attributes].forEach(attr=>{if(/^on/i.test(attr.name)||/javascript:/i.test(attr.value))el.removeAttribute(attr.name)}));return doc.body.innerHTML}
function topicFor(name){return(data.topics||[]).find(t=>t.name===name)||{color:"#dfc4a9",icon:"✦"}}
function displayDate(value){const d=String(value||"");if(!/^\d{4}-\d{2}-\d{2}$/.test(d))return d;return new Intl.DateTimeFormat("en-US",{month:"long",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${d}T00:00:00Z`))}
function readingTime(post){const html=post.content?new DOMParser().parseFromString(post.content,"text/html").body.textContent||"":"";const text=html||[post.lead,...(post.body||[]),post.quote].filter(Boolean).join(" ");const words=text.trim().split(/\s+/).filter(Boolean).length;return `${Math.max(1,Math.ceil(words/220))} min read`}
function showToast(message){$(".toast").textContent=message;$(".toast").classList.add("show");setTimeout(()=>$(".toast").classList.remove("show"),3000)}
function siteName(){return control.site?.name||"TAMORA"}
function notFound(){document.title=`Story not found — ${siteName()}`;$("#article").innerHTML='<div class="not-found"><p class="eyebrow">A missing page</p><h1>This story is not published.</h1><p><a href="index.html#journal">Return to the journal →</a></p></div>';$("#related").hidden=true}
function ensureMeta(property,name){let el=property?$(`meta[property="${property}"]`):$(`meta[name="${name}"]`);if(!el){el=document.createElement('meta');if(property)el.setAttribute('property',property);else el.setAttribute('name',name);document.head.appendChild(el)}return el}
function buildToc(){const body=$("#article-body"),heads=$$("h2,h3",body);if(heads.length<2)return;const toc=document.createElement('nav');toc.className='article-toc';toc.innerHTML='<p>On this page</p>';const list=document.createElement('ol');heads.forEach((h,i)=>{if(!h.id)h.id=`section-${i+1}-${slugify(h.textContent).slice(0,40)}`;const li=document.createElement('li');if(h.tagName==='H3')li.className='toc-sub';const a=document.createElement('a');a.href=`#${h.id}`;a.textContent=h.textContent;li.appendChild(a);list.appendChild(li)});toc.appendChild(list);body.before(toc)}
function renderPrevNext(post){const all=(data.posts||[]).filter(isPublished);const index=all.indexOf(post);const prev=all[index-1],next=all[index+1];if(!prev&&!next)return;const nav=document.createElement('nav');nav.className='post-pagination';nav.innerHTML=`${prev?`<a class="prev-post" href="story.html?story=${encodeURIComponent(prev.slug||slugify(prev.title))}"><span>← Previous</span><strong>${escapeHtml(prev.title)}</strong></a>`:'<span></span>'}${next?`<a class="next-post" href="story.html?story=${encodeURIComponent(next.slug||slugify(next.title))}"><span>Next →</span><strong>${escapeHtml(next.title)}</strong></a>`:''}`;$("#article-body").after(nav)}
function relatedPosts(post){const published=(data.posts||[]).filter(p=>p!==post&&isPublished(p));const manual=(post.relatedSlugs||[]).map(slug=>published.find(p=>(p.slug||slugify(p.title))===slug)).filter(Boolean);if(manual.length)return manual.slice(0,3);const tags=new Set(post.tags||[]);return published.sort((a,b)=>{const score=x=>(x.category===post.category?3:0)+(x.tags||[]).filter(t=>tags.has(t)).length;return score(b)-score(a)}).slice(0,3)}
function render(post){const topic=topicFor(post.category),description=post.seoDescription||post.excerpt,author=post.author||control.site?.authorName||"Tam Phan";document.title=`${post.seoTitle||post.title} — ${siteName()}`;$("#meta-description").content=description;$("#og-title").content=post.seoTitle||post.title;$("#og-description").content=description;if(post.socialImage||post.image)ensureMeta('og:image').content=post.socialImage||post.image;ensureMeta(null,'twitter:card').content='summary_large_image';
  const updated=post.updatedDate&&post.updatedDate!==post.date?`<span>Updated ${escapeHtml(displayDate(post.updatedDate))}</span>`:"";$("#article-meta").innerHTML=`<span>${escapeHtml(post.category)}</span>${post.date?`<span>Published ${escapeHtml(displayDate(post.date))}</span>`:""}${updated}<span>${escapeHtml(readingTime(post))}</span>`;$("#article-title").textContent=post.title;$("#article-excerpt").textContent=post.excerpt;$("#article-byline").textContent=`By ${author}`;$("#article-cover").style.setProperty("--cover-color",post.color||topic.color);$("#article-cover").innerHTML=post.image?`<img src="${escapeHtml(post.image)}" alt="${escapeHtml(post.title)}">`:`<span class="art-shape a"></span><span class="art-shape b"></span><span class="art-line"></span><span class="art-topic">${escapeHtml(topic.icon)}</span>`;
  const paragraphs=(post.body||[]).map((p,i)=>`${i===1&&post.quote?`<blockquote class="article-quote">“${escapeHtml(post.quote)}”</blockquote>`:""}<p>${escapeHtml(p)}</p>`).join("");const content=post.content?safeRichHtml(post.content):paragraphs;$("#article-body").innerHTML=`${post.lead?`<p><strong>${escapeHtml(post.lead)}</strong></p>`:""}${content}<div class="article-tags">${(post.tags||[]).map(t=>`<span>#${escapeHtml(t)}</span>`).join("")}</div>`;buildToc();renderPrevNext(post);
  const related=relatedPosts(post);$("#related-grid").innerHTML=related.map(p=>{const t=topicFor(p.category);return`<a class="related-card" href="story.html?story=${encodeURIComponent(p.slug||slugify(p.title))}"><span class="related-swatch" style="--card-color:${p.color||t.color}">${t.icon}</span><span class="related-copy"><span>${escapeHtml(p.category)}</span><h3>${escapeHtml(p.title)}</h3></span></a>`}).join("");if(!related.length)$("#related").hidden=true}
async function init(){try{const [siteRes,controlRes]=await Promise.all([fetch(`content/site.json?fresh=${Date.now()}`,{cache:"no-store"}),fetch(`content/control.json?fresh=${Date.now()}`,{cache:"no-store"})]);data=siteRes.ok?await siteRes.json():{posts:[],topics:[]};control=controlRes.ok?await controlRes.json():{}}catch{notFound();return}const slug=new URLSearchParams(location.search).get("story");const post=(data.posts||[]).find(p=>(p.slug||slugify(p.title))===slug);if(!post||!isPublished(post)){notFound();return}render(post);$("#year").textContent=new Date().getFullYear()}
$("#copy-link").onclick=async()=>{await navigator.clipboard.writeText(location.href);showToast("Story link copied ♡")};$("#share-native").onclick=async()=>{if(navigator.share){await navigator.share({title:document.title,url:location.href})}else{await navigator.clipboard.writeText(location.href);showToast("Story link copied ♡")}};addEventListener("scroll",()=>{const max=document.documentElement.scrollHeight-innerHeight;$(".reading-progress span").style.width=`${max?scrollY/max*100:0}%`},{passive:true});init();