(()=>{
  const STORAGE_KEY='softly-tam-color-mode';
  const OLD_KEY='site-color-mode';
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>[...r.querySelectorAll(s)];
  let allowToggle=true,defaultMode='light',controlData={};
  async function loadControl(){try{const r=await fetch('content/control.json?v='+Date.now(),{cache:'no-store'});return r.ok?await r.json():{}}catch{return{}}}
  function getSavedMode(){const current=localStorage.getItem(STORAGE_KEY);if(current==='light'||current==='dark')return current;const old=localStorage.getItem(OLD_KEY);if(old==='light'||old==='dark'){localStorage.setItem(STORAGE_KEY,old);localStorage.removeItem(OLD_KEY);return old}return''}
  function currentMode(){return getSavedMode()||defaultMode}
  function applyDesign(){const d=controlData.design||{},r=document.documentElement;if(d.primaryColor)r.style.setProperty('--light-ink',d.primaryColor);if(d.backgroundColor)r.style.setProperty('--light-bg',d.backgroundColor);if(d.surfaceColor)r.style.setProperty('--light-surface',d.surfaceColor);if(d.accentColor)r.style.setProperty('--light-accent',d.accentColor);if(d.mutedColor)r.style.setProperty('--light-muted',d.mutedColor)}
  function applyMode(mode){const dark=mode==='dark';document.body.classList.toggle('color-mode-dark',dark);document.documentElement.dataset.colorMode=dark?'dark':'light';const meta=$('meta[name="theme-color"]');if(meta)meta.content=dark?'#1d1a18':'#fbf7f0';$$('.theme-toggle-unified').forEach(btn=>{btn.setAttribute('aria-pressed',String(dark));btn.setAttribute('aria-label',dark?'Switch to light mode':'Switch to dark mode');btn.replaceChildren();const icon=document.createElement('span');icon.className='theme-icon';icon.textContent=dark?'☀':'☾';const text=document.createElement('span');text.textContent=dark?'Light':'Dark';btn.append(icon,text)})}
  function removeLegacy(){$$('.theme-toggle,.article-theme-toggle').forEach(el=>el.remove())}
  function installToggle(){removeLegacy();if(!allowToggle){$$('.theme-toggle-unified').forEach(el=>el.remove());return}let btn=$('.theme-toggle-unified');if(!btn){btn=document.createElement('button');btn.type='button';btn.className='theme-toggle-unified';const host=$('.utility-links')||$('.article-header-actions')||$('.site-header');if(host)host.prepend(btn);btn.addEventListener('click',()=>{const next=document.body.classList.contains('color-mode-dark')?'light':'dark';localStorage.setItem(STORAGE_KEY,next);localStorage.removeItem(OLD_KEY);applyMode(next)})}applyMode(currentMode())}
  function installMotion(){document.body.classList.add('motion-calm');document.body.classList.remove('animation-strong','animation-slide','animation-zoom','animation-fast')}
  function syncGlobalBrand(){const site=controlData.site||{};if(site.name)$$('[data-site-name]').forEach(el=>el.textContent=site.name);if(site.authorName)$$('[data-author-name]').forEach(el=>el.textContent=site.authorName);const byline=$('#article-byline');if(byline&&site.authorName&&(!byline.textContent.trim()||byline.textContent.trim()==='By Tam Phan'))byline.textContent='By '+site.authorName;if(site.name&&$('#article-title')&&document.title.includes(' — '))document.title=document.title.split(' — ')[0]+' — '+site.name}
  function loadOnce(src,id){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.defer=true;document.body.appendChild(s)}
  function installCmsHooks(){if($('#top')){loadOnce('home-sync.js?v=1','home-sync-loader');loadOnce('contact-control.js?v=1','contact-control-loader')}}
  function reconcile(){applyDesign();removeLegacy();applyMode(currentMode());installToggle();installMotion();syncGlobalBrand();installCmsHooks()}
  async function init(){controlData=await loadControl();const design=controlData.design||{};allowToggle=design.allowVisitorDarkMode!==false;defaultMode=design.defaultMode==='dark'?'dark':'light';reconcile();[650,1300,2400,4000].forEach(ms=>setTimeout(reconcile,ms));window.addEventListener('storage',e=>{if(e.key===STORAGE_KEY||e.key===OLD_KEY)reconcile()})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();